/** Error payloads are rebuilt from an allowlist, not regex-redacted raw content. */
const errorTypes = new Set([
  "Error",
  "TypeError",
  "ReferenceError",
  "SyntaxError",
  "RangeError",
  "URIError",
  "EvalError",
  "AggregateError",
  "TRPCError",
]);

function record(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function compiledFilename(value: unknown): string | undefined {
  if (typeof value !== "string") return;
  const path = value.split(/[?#]/)[0] ?? "";
  // Only emitted Next chunks or bundled server entries. Never include local source/repo paths.
  const next = path.match(/\/_next\/static\/(?:chunks|[^/]+)\/[A-Za-z0-9_./~()-]+\.js$/);
  if (next && !next[0].includes("..")) return next[0];
  const bundled = path.match(
    /(?:^|\/)(index|instrumentation|server)(?:[.-][A-Za-z0-9_-]+)?\.(?:mjs|js)$/,
  );
  return bundled ? bundled[0].replace(/^\//, "") : undefined;
}

function frame(value: unknown) {
  const original = record(value);
  const filename = compiledFilename(original.filename);
  const chunkId =
    typeof original.chunk_id === "string" && /^[a-f0-9-]{32,36}$/i.test(original.chunk_id)
      ? original.chunk_id
      : undefined;
  if (!filename && !chunkId) return [];
  return [
    {
      platform: original.platform === "node:javascript" ? "node:javascript" : "web:javascript",
      ...(filename ? { filename } : {}),
      ...(chunkId ? { chunk_id: chunkId } : {}),
      ...(typeof original.lineno === "number" &&
      Number.isSafeInteger(original.lineno) &&
      original.lineno > 0
        ? { lineno: original.lineno }
        : {}),
      ...(typeof original.colno === "number" &&
      Number.isSafeInteger(original.colno) &&
      original.colno >= 0
        ? { colno: original.colno }
        : {}),
      ...(typeof original.in_app === "boolean" ? { in_app: original.in_app } : {}),
    },
  ];
}

export function sanitizeExceptionProperties(
  properties: Record<string, unknown>,
): Record<string, unknown> | null {
  if (!Array.isArray(properties.$exception_list) || properties.$exception_list.length === 0)
    return null;
  const exceptions = properties.$exception_list.slice(0, 5).map((value) => {
    const original = record(value);
    const type =
      typeof original.type === "string" && errorTypes.has(original.type) ? original.type : "Error";
    const stacktrace = record(original.stacktrace);
    const mechanism = record(original.mechanism);
    return {
      type,
      value: `${type}: details redacted`,
      mechanism: {
        handled: mechanism.handled === true,
        synthetic: mechanism.synthetic === true,
        type: mechanism.handled === true ? "generic" : "onerror",
      },
      ...(Array.isArray(stacktrace.frames)
        ? { stacktrace: { type: "raw", frames: stacktrace.frames.slice(-50).flatMap(frame) } }
        : {}),
    };
  });
  // Keep only correlation fields generated by the SDK, never custom request/user data.
  const result: Record<string, unknown> = {
    $exception_list: exceptions,
    $exception_level: "error",
    $exception_type: exceptions[0]?.type,
    $exception_message: exceptions[0]?.value,
    service: properties.service === "server" ? "server" : "web",
    schema_version: 2,
  };
  for (const key of [
    "distinct_id",
    "$device_id",
    "$session_id",
    "$window_id",
    "$user_id",
    "$lib",
    "$lib_version",
    "$exception_release",
    "$release_id",
  ]) {
    const value = properties[key];
    if (typeof value === "string" && /^[A-Za-z0-9_.:-]{1,200}$/.test(value)) result[key] = value;
  }
  for (const key of ["$is_identified", "$process_person_profile"]) {
    if (typeof properties[key] === "boolean") result[key] = properties[key];
  }
  return result;
}

/** Expected rejections are product outcomes, not operational incidents. */
export function isUnexpectedError(error: unknown): boolean {
  const original = record(error);
  if (original.name === "AbortError") return false;
  const code = record(original.data).code ?? original.code;
  return ![
    "BAD_REQUEST",
    "UNAUTHORIZED",
    "FORBIDDEN",
    "NOT_FOUND",
    "CONFLICT",
    "TOO_MANY_REQUESTS",
    "CLIENT_CLOSED_REQUEST",
  ].includes(String(code));
}
