export { createGittermClient, type GittermClient, type GittermClientOptions } from "./client.js";
export {
  DEFAULT_GITTERM_SERVER_URL,
  getConfigPath,
  loadConfig,
  loadConfigSync,
  saveConfig,
  deleteConfig,
} from "./config.js";
export type { CliConfig } from "./config.js";
export { loginWithDeviceCode } from "./device-login.js";
export type { DeviceCodeInfo, LoginWithDeviceCodeOptions } from "./device-login.js";
export { AgentRunError, GittermError, WorkspaceLifecycleError } from "./errors.js";
export {
  createGittermWorkspaceClient,
  getWorkspaceEnvironment,
  type GittermWorkspaceClient,
  type WorkspaceClientOptions,
  type WorkspaceEnvironment,
  type WorkspacePort,
  type WorkspaceSelf,
} from "./workspace-client.js";
export type {
  CredentialErrorCode,
  GittermErrorCode,
  WorkspaceLifecycleErrorCode,
} from "./errors.js";
export type {
  AgentPermissionRequest,
  AgentQuestion,
  AgentQuestionOption,
  AgentQuestionRequest,
  AgentRun,
  AgentRunCreateInput,
  AgentRunInputRequest,
  AgentRunMessage,
  AgentRunMessagePart,
  AgentRunReply,
  AgentRunStatus,
  AgentRunEvent,
  AgentRunResult,
  AgentRunReplyPermission,
  AgentRunReplyQuestion,
  RunResultOptions,
  RunRef,
  RunWaitOptions,
  RunWatchOptions,
  OpencodeApi,
  AgentType,
  AgentKey,
  AuthStatus,
  BuiltInAgentKey,
  CloudProvider,
  ProviderKey,
  Workspace,
  WorkspaceCreateInput,
  WorkspaceCreateResult,
  WorkspaceCatalog,
  WorkspaceEnsureRunningResult,
  WorkspaceHostingType,
  WorkspaceListOptions,
  WorkspaceListResult,
  WorkspaceRestartResult,
  WorkspaceRuntimeAccess,
  WorkspaceStatus,
  WorkspaceSetupStatus,
  ModelCredential,
  ModelProviderInfo,
  ModelInfo,
  ModelCredentialSource,
  WorkspaceModelsInput,
  WorkspaceModelAccess,
  WorkspacePauseResult,
  WorkspaceTerminateResult,
  WorkspaceProviderSelection,
} from "./types.js";
