AWSTemplateFormatVersion: "2010-09-09"
Description: gitterm – Cross-Account Role for EC2 Provisioning

Resources:
  gittermProvisioningRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: gittermProvisioningRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:user/gitterm-integration"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: gittermEC2Provisioning
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:RunInstances
                  - ec2:DescribeInstances
                  - ec2:TerminateInstances
                  - ec2:CreateTags
                Resource: "*"

Outputs:
  RoleArn:
    Value: !GetAtt gittermProvisioningRole.Arn
    Description: ARN of the cross-account EC2 provisioning role
